// zk-ml/script/src/main.rs — Third Eye SP1 Host / Prover CLI
//
// This binary runs on the HOST machine (not inside the zkVM).  It:
//   1. Loads model_weights.json and tx_input.json from disk.
//   2. Serializes them into the SP1 stdin stream.
//   3. Executes the guest program inside the SP1 zkVM.
//   4. Generates a Groth16 or PLONK proof (configurable via --mode).
//   5. Saves the serialized proof to an output .json file.
//
// Usage:
//   cargo run --release --bin prove -- \
//       --model    zk-ml/model_weights.json \
//       --tx-input /tmp/thirdeye_tx_input.json \
//       --output   /tmp/thirdeye_proof.json \
//       --threshold 0.65 \
//       --mode     groth16
//
// Exit code 0 = proof generated successfully.
// Exit code 1 = any error (model file missing, proof failure, etc.)

use std::path::PathBuf;
use std::time::Instant;

use clap::{Parser, ValueEnum};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use sp1_sdk::{include_elf, ProverClient, SP1ProofWithPublicValues, SP1Stdin};
use tracing::{error, info, warn};

/// ELF of the compiled guest program (embedded at compile time by sp1-build).
pub const THIRDEYE_ELF: sp1_sdk::Elf = include_elf!("thirdeye-zkml-program");

// ── CLI arguments ─────────────────────────────────────────────────────────────

#[derive(Debug, Clone, ValueEnum)]
enum ProofMode {
    /// Fast simulation (no ZK proof) — for local development / testing
    Simulate,
    /// Full SP1 STARK proof (large but fast to generate)
    Core,
    /// Groth16 wrapping (small EVM-verifiable proof, slower to generate)
    Groth16,
    /// PLONK wrapping (EVM-verifiable, also compact)
    Plonk,
}

#[derive(Parser, Debug)]
#[command(
    name        = "thirdeye-prover",
    version     = "0.1.0",
    about       = "Third Eye SP1 zkML Prover — generates a ZK proof of Isolation Forest scoring",
    long_about  = None,
)]
struct Cli {
    /// Path to model_weights.json (output of export_model.py)
    #[arg(long, default_value = "zk-ml/model_weights.json")]
    model: PathBuf,

    /// Path to tx_input.json (generated by FastAPI ml_engine.py)
    #[arg(long)]
    tx_input: PathBuf,

    /// Path to write the proof JSON output
    #[arg(long, default_value = "/tmp/thirdeye_proof.json")]
    output: PathBuf,

    /// Maximum risk threshold — proof fails if anomaly_score >= threshold
    #[arg(long, default_value_t = 0.65_f64)]
    threshold: f64,

    /// Proof mode
    #[arg(long, value_enum, default_value_t = ProofMode::Core)]
    mode: ProofMode,
}

// ── Shared input type (mirrors guest structs for JSON construction) ────────────

#[derive(Serialize, Deserialize, Debug)]
struct TxInputJson {
    tx_id:               String,
    features:            Vec<f64>,
    max_risk_threshold:  f64,
}

/// Output written to disk — the proof + its public values.
#[derive(Serialize, Deserialize, Debug)]
struct ProofResult {
    tx_id:            String,
    is_safe:          bool,
    anomaly_score:    f64,   // Reconstructed from fixed-point
    threshold:        f64,
    proof_bytes_b64:  String,
    public_values:    Value,
    proving_time_ms:  u64,
    proof_mode:       String,
}

#[tokio::main]
async fn main() {
    // Initialise structured logging (level controlled via RUST_LOG env var)
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::EnvFilter::from_default_env())
        .init();

    let cli = Cli::parse();

    info!("Third Eye SP1 v6 Prover starting");
    info!("  model    : {:?}", cli.model);
    info!("  tx_input : {:?}", cli.tx_input);
    info!("  threshold: {}", cli.threshold);
    info!("  mode     : {:?}", cli.mode);

    // ── Load model_weights.json ───────────────────────────────────────────
    let model_raw = std::fs::read_to_string(&cli.model).unwrap_or_else(|e| {
        error!("Cannot read model file {:?}: {}", cli.model, e);
        std::process::exit(1);
    });
    let _model_check: Value = serde_json::from_str(&model_raw).unwrap_or_else(|e| {
        error!("model_weights.json is not valid JSON: {}", e);
        std::process::exit(1);
    });
    info!("Model loaded ({} bytes)", model_raw.len());

    // ── Load tx_input.json ────────────────────────────────────────────────
    let tx_raw = std::fs::read_to_string(&cli.tx_input).unwrap_or_else(|e| {
        error!("Cannot read tx_input file {:?}: {}", cli.tx_input, e);
        std::process::exit(1);
    });
    let mut tx_input: TxInputJson = serde_json::from_str(&tx_raw).unwrap_or_else(|e| {
        error!("tx_input.json parse error: {}", e);
        std::process::exit(1);
    });

    tx_input.max_risk_threshold = cli.threshold;
    info!("TxInput: id={}, features={}", tx_input.tx_id, tx_input.features.len());

    // ── Build SP1 stdin ───────────────────────────────────────────────────
    let mut stdin = SP1Stdin::new();
    stdin.write_slice(model_raw.as_bytes());
    let tx_json_bytes = serde_json::to_vec(&tx_input).expect("tx_input serialization failed");
    stdin.write_slice(&tx_json_bytes);

    // ── Set up SP1 ProverClient (v6: async builder, reads SP1_PROVER env var) ─
    let client = ProverClient::builder().build().await;
    let (pk, vk) = client.setup(THIRDEYE_ELF).await;
    info!("SP1 proving key set up.");

    // ── Execute / Prove ───────────────────────────────────────────────────
    let t0 = Instant::now();

    let proof: SP1ProofWithPublicValues = match cli.mode {
        ProofMode::Simulate => {
            warn!("Running in SIMULATE mode — no cryptographic proof generated.");
            let (_pv, _report) = client
                .execute(THIRDEYE_ELF, &stdin)
                .run()
                .await
                .unwrap_or_else(|e| {
                    error!("SP1 execution failed: {}", e);
                    std::process::exit(1);
                });
            info!("Simulation OK. Use --mode core for a real proof.");
            panic!("Simulate mode does not produce a proof.");
        }

        ProofMode::Core => {
            info!("Generating SP1 Core (STARK) proof...");
            client
                .prove(&pk, &stdin)
                .run()
                .await
                .unwrap_or_else(|e| {
                    error!("Core proof failed: {}", e);
                    std::process::exit(1);
                })
        }

        ProofMode::Groth16 => {
            info!("Generating Groth16 proof (EVM-verifiable)...");
            client
                .prove(&pk, &stdin)
                .groth16()
                .run()
                .await
                .unwrap_or_else(|e| {
                    error!("Groth16 proof failed: {}", e);
                    std::process::exit(1);
                })
        }

        ProofMode::Plonk => {
            info!("Generating PLONK proof (EVM-verifiable)...");
            client
                .prove(&pk, &stdin)
                .plonk()
                .run()
                .await
                .unwrap_or_else(|e| {
                    error!("PLONK proof failed: {}", e);
                    std::process::exit(1);
                })
        }
    };

    let elapsed_ms = t0.elapsed().as_millis() as u64;
    info!("Proof generated in {}ms", elapsed_ms);

    // ── Verify proof locally ──────────────────────────────────────────────
    client.verify(&proof, &vk).await.unwrap_or_else(|e| {
        error!("Proof verification failed: {}", e);
        std::process::exit(1);
    });
    info!("Proof verified OK locally.");

    // ── Extract public values ─────────────────────────────────────────────
    // The guest committed: ProofOutput { tx_id, is_safe, anomaly_score_fp, threshold_fp }
    let mut public_values = proof.public_values.clone();
    let _tx_id_out:       String = public_values.read::<String>();
    let is_safe:          bool   = public_values.read::<bool>();
    let anomaly_score_fp: u32    = public_values.read::<u32>();
    let threshold_fp:     u32    = public_values.read::<u32>();

    let anomaly_score = anomaly_score_fp as f64 / 1_000_000.0;
    let threshold_out = threshold_fp as f64 / 1_000_000.0;

    info!(
        "Public outputs: is_safe={}, anomaly_score={:.6}, threshold={:.6}",
        is_safe, anomaly_score, threshold_out
    );

    // ── Serialize proof to disk ───────────────────────────────────────────
    // We use SP1's built-in bincode serialization and then base64-encode for JSON.
    let proof_bytes = bincode::serialize(&proof).unwrap_or_else(|e| {
        error!("Failed to serialize proof: {}", e);
        std::process::exit(1);
    });
    let proof_b64 = base64_encode(&proof_bytes);

    let result = ProofResult {
        tx_id:           tx_input.tx_id.clone(),
        is_safe,
        anomaly_score,
        threshold:       threshold_out,
        proof_bytes_b64: proof_b64,
        public_values:   serde_json::json!({
            "is_safe": is_safe,
            "anomaly_score_fp": anomaly_score_fp,
            "threshold_fp": threshold_fp,
        }),
        proving_time_ms: elapsed_ms,
        proof_mode: format!("{:?}", cli.mode),
    };

    let result_json = serde_json::to_string_pretty(&result)
        .expect("Result serialization failed");

    std::fs::write(&cli.output, &result_json).unwrap_or_else(|e| {
        error!("Cannot write proof to {:?}: {}", cli.output, e);
        std::process::exit(1);
    });

    info!("Proof written to {:?} ({} bytes)", cli.output, result_json.len());
    println!("{{\"success\":true,\"anomaly_score\":{},\"is_safe\":{},\"proof_path\":\"{}\"}}", 
             anomaly_score, is_safe, cli.output.display());
}

/// Minimal base64 encoder (no external dep needed for hex/b64 at hackathon scale).
fn base64_encode(data: &[u8]) -> String {
        // Use standard library's built-in base64 (available via std in Rust 1.70+
    // through the `base64` alphabet).  For simplicity we use a simple impl.
    const CHARS: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = Vec::with_capacity((data.len() + 2) / 3 * 4);
    for chunk in data.chunks(3) {
        let b0 = chunk[0] as usize;
        let b1 = if chunk.len() > 1 { chunk[1] as usize } else { 0 };
        let b2 = if chunk.len() > 2 { chunk[2] as usize } else { 0 };
        out.push(CHARS[(b0 >> 2) & 0x3F]);
        out.push(CHARS[((b0 << 4) | (b1 >> 4)) & 0x3F]);
        out.push(if chunk.len() > 1 { CHARS[((b1 << 2) | (b2 >> 6)) & 0x3F] } else { b'=' });
        out.push(if chunk.len() > 2 { CHARS[b2 & 0x3F] } else { b'=' });
    }
    String::from_utf8(out).unwrap()
}
